#!/bin/sh

project="schizo_diary"

if [ "$1" = "build" ] || [ "$1" = "make" ]
then
    cmake -B build/cmake/ -S .
    make -C build/cmake/
elif [ "$1" = "rebuild" ]
then 
    rm -rf build/bin/* build/cmake/*
    cmake -B build/cmake/ -S . 
    make -C build/cmake/
elif [ "$1" = "clean" ]
then
    rm -rf build/
    if [ -e cmake-build-debug/ ]
    then
      rm -rf cmake-build-debug/
    fi
elif [ "$1" = "help" ]
then
    echo -e "Build project:\t ./run build"
    echo -e "Rebuild project: ./run rebuild"
    echo -e "Clean project:\t ./run clean"
    echo -e "Run project:\t ./run"
else 
    if [ -e build/bin/$project ]
    then
        exec build/bin/$project "$@"
    else 
        echo "No binary executable named \"$project\" found in the directory \"build/bin/\"."
        echo "Building..."

        cmake -B build/cmake/ -S .
        make -C build/cmake/
    fi
fi
